name: Gitlab-Mirror
on: [push]
jobs:
  Gitlab-Mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Gitlab Mirror
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/tedmdelacruz/mirror-test"
        env:
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "tedmdelacruz"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "32789226"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}